services:
  hs300-exporter:
    image: hs300-exporter:latest
    container_name: hs300-exporter
    restart: unless-stopped
    ports:
      - "9300:9999"
    environment:
      - TZ=Asia/Taipei
      - HS300_DeviceIP=192.168.1.1
    healthcheck:
      test: |
        bash -c 'usage=$$(ps aux | grep dotnet | grep -v grep | awk '\''{print $$3}\'' | head -1) && 
        [ $$(echo "$$usage > 80" | bc) -eq 1 ] && kill -s 15 1 || exit 0'
      interval: 10s
      timeout: 5s
      retries: 3
