services:
  hs300-exporter:
    image: hs300-exporter:latest
    container_name: hs300-exporter
    restart: unless-stopped
    ports:
      - "9300:9999"
    environment:
      - TZ=Asia/Taipei
      - HS300_DeviceIP=192.168.1.1
    network_mode: bridge
